-- SQL Script to run in Supabase SQL Editor

-- 1. Create Teams Table
create table public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tournament_id text default 'default'
);

-- 2. Create Matches Table
create table public.matches (
  id text primary key, -- we use string IDs like '123-456' or 'semi1'
  group_name text not null,
  team_a_id bigint references public.teams(id),
  team_b_id bigint references public.teams(id),
  score jsonb default null, -- stores { set1: {a:0, b:0}, ... }
  winner_id bigint references public.teams(id),
  phase int not null, -- 2, 3, 4
  tournament_id text default 'default',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Settings Table (to store global state like current Phase, MiniGroups)
create table public.settings (
  key text primary key,
  value jsonb
);

-- 4. Enable Realtime
alter publication supabase_realtime add table public.teams;
alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.settings;

-- 5. Policies (Optional: Enable read/write for everyone for this demo)
alter table public.teams enable row level security;
create policy "Public Access Teams" on public.teams for all using (true) with check (true);

alter table public.matches enable row level security;
create policy "Public Access Matches" on public.matches for all using (true) with check (true);

alter table public.settings enable row level security;
create policy "Public Access Settings" on public.settings for all using (true) with check (true);

